// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Admin__AutosubmitController from "./admin/autosubmit_controller"
application.register("admin--autosubmit", Admin__AutosubmitController)

import Admin__ProtectedVariablesController from "./admin/protected_variables_controller"
application.register("admin--protected-variables", Admin__ProtectedVariablesController)

import Admin__RoleSelectController from "./admin/role_select_controller"
application.register("admin--role-select", Admin__RoleSelectController)

import Admin__UserSearchController from "./admin/user_search_controller"
application.register("admin--user-search", Admin__UserSearchController)

import Auth__AddCredentialController from "./auth/add_credential_controller"
application.register("auth--add-credential", Auth__AddCredentialController)

import Auth__CredentialAuthenticatorController from "./auth/credential_authenticator_controller"
application.register("auth--credential-authenticator", Auth__CredentialAuthenticatorController)

import Auth__TotpFormController from "./auth/totp_form_controller"
application.register("auth--totp-form", Auth__TotpFormController)

import Base__FormController from "./base/form_controller"
application.register("base--form", Base__FormController)

import Charts__BaseController from "./charts/base_controller"
application.register("charts--base", Charts__BaseController)

import Charts__ChartController from "./charts/chart_controller"
application.register("charts--chart", Charts__ChartController)

import Charts__ReportsChartController from "./charts/reports_chart_controller"
application.register("charts--reports-chart", Charts__ReportsChartController)

import Charts__ToggleController from "./charts/toggle_controller"
application.register("charts--toggle", Charts__ToggleController)

import DebugController from "./debug_controller"
application.register("debug", DebugController)

import Forms__ApplicationFormController from "./forms/application_form_controller"
application.register("forms--application-form", Forms__ApplicationFormController)

import Forms__AutosaveController from "./forms/autosave_controller"
application.register("forms--autosave", Forms__AutosaveController)

import Forms__ContactFeedbackController from "./forms/contact_feedback_controller"
application.register("forms--contact-feedback", Forms__ContactFeedbackController)

import Forms__CurrencyFormatterController from "./forms/currency_formatter_controller"
application.register("forms--currency-formatter", Forms__CurrencyFormatterController)

import Forms__DateRangeController from "./forms/date_range_controller"
application.register("forms--date-range", Forms__DateRangeController)

import Forms__DependentFieldsController from "./forms/dependent_fields_controller"
application.register("forms--dependent-fields", Forms__DependentFieldsController)

import Forms__DependentSelectorController from "./forms/dependent_selector_controller"
application.register("forms--dependent-selector", Forms__DependentSelectorController)

import Forms__IncomeValidationController from "./forms/income_validation_controller"
application.register("forms--income-validation", Forms__IncomeValidationController)

import Forms__PaperApplicationController from "./forms/paper_application_controller"
application.register("forms--paper-application", Forms__PaperApplicationController)

import Forms__RejectionFormController from "./forms/rejection_form_controller"
application.register("forms--rejection-form", Forms__RejectionFormController)

import Reviews__EvaluationManagementController from "./reviews/evaluation_management_controller"
application.register("reviews--evaluation-management", Reviews__EvaluationManagementController)

import Reviews__ProofStatusController from "./reviews/proof_status_controller"
application.register("reviews--proof-status", Reviews__ProofStatusController)

import Reviews__W9ReviewController from "./reviews/w9_review_controller"
application.register("reviews--w9-review", Reviews__W9ReviewController)

import Ui__AccessibilityAnnouncerController from "./ui/accessibility_announcer_controller"
application.register("ui--accessibility-announcer", Ui__AccessibilityAnnouncerController)

import Ui__CheckboxSelectAllController from "./ui/checkbox_select_all_controller"
application.register("ui--checkbox-select-all", Ui__CheckboxSelectAllController)

import Ui__MobileMenuController from "./ui/mobile_menu_controller"
application.register("ui--mobile-menu", Ui__MobileMenuController)

import Ui__ModalController from "./ui/modal_controller"
application.register("ui--modal", Ui__ModalController)

import Ui__PdfLoaderController from "./ui/pdf_loader_controller"
application.register("ui--pdf-loader", Ui__PdfLoaderController)

import Ui__ReportsToggleController from "./ui/reports_toggle_controller"
application.register("ui--reports-toggle", Ui__ReportsToggleController)

import Ui__StreamReadyController from "./ui/stream_ready_controller"
application.register("ui--stream-ready", Ui__StreamReadyController)

import Ui__UploadController from "./ui/upload_controller"
application.register("ui--upload", Ui__UploadController)

import Ui__VisibilityController from "./ui/visibility_controller"
application.register("ui--visibility", Ui__VisibilityController)

import Users__ApplicantTypeController from "./users/applicant_type_controller"
application.register("users--applicant-type", Users__ApplicantTypeController)

import Users__DocumentProofHandlerController from "./users/document_proof_handler_controller"
application.register("users--document-proof-handler", Users__DocumentProofHandlerController)

import Users__GuardianPickerController from "./users/guardian_picker_controller"
application.register("users--guardian-picker", Users__GuardianPickerController)
