# Omakase Ruby styling for Rails

# Load RuboCop extension libraries
plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

# Target Rails version
AllCops:
  TargetRailsVersion: 8.0
  NewCops: enable

# Customize line length
Layout/LineLength:
  Max: 165

# Customize class size limits
Metrics/ClassLength:
  Max: 300

# Customize method size limits
Metrics/MethodLength:
  Max: 30

# Allow custom find_by methods that provide encryption support and error handling
Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email
    - find_by_phone
    - find_by_token_for

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
