# Load RuboCop extension libraries
plugins:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

# Target Rails version
AllCops:
  TargetRailsVersion: 8.0
  NewCops: enable
  Exclude:
  - 'db/schema.rb'
  - 'db/queue_schema.rb'
  - 'bin/*'
  - 'vendor/**/*'
  - 'node_modules/**/*'
  - 'tmp/**/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
  - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 18
  Exclude:
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 12
  Exclude:
  - 'test/**/*'

# Customize line length
Layout/LineLength:
  Max: 170
  Exclude:
    - 'test/**/*'

# Customize class size limits
Metrics/ClassLength:
  Max: 600
  Exclude:
    - 'test/**/*'

# Customize module size limits
Metrics/ModuleLength:
  Max: 280
  Exclude:
    - 'test/**/*'

# Customize method size limits
Metrics/MethodLength:
  Max: 80
  Exclude:
    - 'test/**/*'

# Customize block size limits
Metrics/BlockLength:
  Max: 100
  Exclude:
    - 'test/**/*'
    - 'spec/**/*'
    - 'lib/tasks/**/*.rake'
    - 'config/routes.rb'
    - 'db/seeds.rb'

# Allow custom find_by methods that provide encryption support and error handling
Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_email
    - find_by_phone
    - find_by_token_for

# Disable variable number naming enforcement (allow physical_address_1 instead of physical_address1)
Naming/VariableNumber:
  Enabled: false

# Disable frozen string literal comment requirement
Style/FrozenStringLiteralComment:
  Enabled: false

# `has_many :through` is generally better, but refactoring existing HABTM
# associations is a lot of work for little gain if they are working fine.
Rails/HasAndBelongsToMany:
  Enabled: false

# Skipping validations is dangerous in app code but often necessary and safe
# in migrations, seeds, and some tests for performance.
Rails/SkipsModelValidations:
  # Keep this cop enabled by default, but exclude it from safe directories.
  Exclude:
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'test/**/*'
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
