development:
  ELASTIC_EMAIL_API_KEY: your_api_key_here
  ELASTIC_EMAIL_FROM: your_verified_sender@example.com
  ELASTIC_EMAIL_REPLY_TO: replies@example.com
  MAILER_HOST: localhost:3000

test:
  ELASTIC_EMAIL_API_KEY: your_api_key_here
  ELASTIC_EMAIL_FROM: your_verified_sender@example.com
  ELASTIC_EMAIL_REPLY_TO: replies@example.com
  MAILER_HOST: localhost:3000

production:
  ELASTIC_EMAIL_API_KEY: <%= ENV['ELASTIC_EMAIL_API_KEY'] %>
  ELASTIC_EMAIL_FROM: <%= ENV['ELASTIC_EMAIL_FROM'] %>
  ELASTIC_EMAIL_REPLY_TO: <%= ENV['ELASTIC_EMAIL_REPLY_TO'] %>
  MAILER_HOST: <%= ENV['MAILER_HOST'] %>
