# frozen_string_literal: true

Rails.application.configure do
  config.after_initialize do
    Bullet.enable        = true
    Bullet.alert         = true
    Bullet.bullet_logger = true
    Bullet.console       = true
    Bullet.rails_logger  = true
    Bullet.add_footer    = true

    # Replacing an existing has_one_attached file causes Rails internals to
    # eager-load attachment.record before swapping the blob. Bullet reports
    # this as unused eager loading even though the query shape is framework-
    # driven rather than app-level.
    Bullet.add_safelist type: :unused_eager_loading,
                        class_name: 'ActiveStorage::Attachment',
                        association: :record
  end

  config.eager_load = false

  config.active_storage.service = :local

  config.active_storage.content_types_to_serve_as_binary = []

  # Configure default URL options
  Rails.application.routes.default_url_options = {
    host: 'localhost',
    port: 3000
  }

  # Configure headers for PDF serving
  config.action_dispatch.default_headers = {
    'X-Frame-Options' => 'SAMEORIGIN',
    'X-XSS-Protection' => '1; mode=block',
    'X-Content-Type-Options' => 'nosniff',
    'X-Download-Options' => 'noopen',
    'X-Permitted-Cross-Domain-Policies' => 'none',
    'Referrer-Policy' => 'strict-origin-when-cross-origin'
  }

  # Only the non-default and required settings
  config.action_mailer.delivery_method = :letter_opener
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.default_url_options = { host: 'localhost', port: 3000 }

  config.active_job.queue_adapter = :solid_queue
  config.solid_queue.connects_to = { database: { writing: :queue } }

  # Asset pipeline settings
  config.assets.debug = true
  config.assets.digest = true
  config.assets.raise_runtime_errors = true
  config.file_watcher = ActiveSupport::FileUpdateChecker

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  config.generators.apply_rubocop_autocorrect_after_generate!
end
