name: "Rails Tests"

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mat_vulcan_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://postgres:postgres@localhost:5432/mat_vulcan_test"
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres

    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        
      - name: Verify Chrome installation
        run: chrome --version
        
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          
      - name: Install dependencies
        run: |
          yarn install
          bundle install
          
      - name: Build assets
        run: |
          yarn run build
          yarn run build:css
          
      - name: Precompile Rails assets
        run: bin/rails assets:precompile
        env:
          RAILS_ENV: test
          
      - name: Verify assets were built
        run: |
          ls -la app/assets/builds/
          echo "application.css size:" $(wc -c < app/assets/builds/application.css)
          echo "Checking public/assets:"
          ls -la public/assets/ || echo "No public/assets directory"
          
      - name: Setup database
        run: bin/rails db:prepare
        
      - name: Run standard tests
        run: bin/rails test
        
      - name: Run system tests
        run: bin/rails test:system
